Add search bar component
chingu-voyages/v41-geckos-team-18 pull request #30
Opened 2022-10-18 08:27 UTC by funamioh

- Add search bar component referring to  [MUI: App bar](https://mui.com/material-ui/react-app-bar/)

2022-10-19 09:32 UTC, sukyungdev approved these changes

2022-10-20 09:50 UTC, doinby requested changes
Looks fantastic, great start and thank you for adding some stylings. I learn a lot from looking at your code!

A few notes from me:
- I think we could break `searchbar.component.jsx` down to several smaller components so the code is cleaner and easier to make changes in the future
- Please consider writing description for the PR, things like, "Added node-sass dependencies", "Added search bar and basic navigation" 🙏
- It would be really helpful if you could switch naming your component `SearchBar.js` instead of `searchbar.component.jsx` to be consistent with the team. Read more here: [Five best practices for React developers](https://www.educative.io/blog/best-practices-react-developer#5)

I would love to hear your thoughts on this

2022-10-24 22:27 UTC, doinby approved these changes

2022-10-24 22:28 UTC, doinby approved these changes

2022-10-24 22:31 UTC, merged